### ISSUE TITLE
bn.js assertion failure

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/ethereumjs-util#1]
When trying `vapor` I get:

```
info vm processing block: c753d3dc40dce12c4004f84e68f125924f57f655d182b6b3c88bd23b4957aa8bheight: 01
/Users/mids/Projects/ethereum/vapor/node_modules/ethereumjs-lib/node_modules/ethereumjs-util/node_modules/bn.js/lib/bn.js:1326
  assert(num.cmpn(0) !== 0);
             ^
TypeError: undefined is not a function
    at BN.divmod (/Users/mids/Projects/ethereum/vapor/node_modules/ethereumjs-lib/node_modules/ethereumjs-util/node_modules/bn.js/lib/bn.js:1326:14)
    at BN.div (/Users/mids/Projects/ethereum/vapor/node_modules/ethereumjs-lib/node_modules/ethereumjs-util/node_modules/bn.js/lib/bn.js:1373:15)
    at BlockHeader.validatePOW (/Users/mids/Projects/ethereum/vapor/node_modules/ethereumjs-lib/lib/blockHeader.js:78:34)
    at /Users/mids/Projects/ethereum/vapor/node_modules/ethereumjs-lib/lib/blockHeader.js:149:12
    at /Users/mids/Projects/ethereum/vapor/node_modules/node-ethereum/node_modules/ethereumjs-lib/lib/blockchain.js:189:7
    at Stream.<anonymous> (/Users/mids/Projects/ethereum/vapor/node_modules/node-ethereum/node_modules/multilevel/node_modules/rpc-stream/index.js:77:10)
    at Stream.stream.write (/Users/mids/Projects/ethereum/vapor/node_modules/node-ethereum/node_modules/multilevel/node_modules/rpc-stream/node_modules/through/index.js:26:11)
    at Stream.ondata (stream.js:51:26)
    at Stream.emit (events.js:107:17)
    at Stream.<anonymous> (/Users/mids/Projects/ethereum/vapor/node_modules/node-ethereum/node_modules/multilevel/node_modules/mux-demux/inject.js:61:14)
```

**Comment by wanderer** [comment]
sorry @jorisbontjethat is my fault, I will fix immediate

**Comment by jorisbontje** [comment]
Fixed
