### ISSUE TITLE
confusing behaviour

### ISSUE THREAD

**Issue by kumavis** [ethereum/ethereumjs-util#7]
```js
> ethUtil.pad(ethUtil.stripHexPrefix(originalStorageKeyHex), 32)
ReferenceError: originalStorageKeyHex is not defined
    at repl:1:36
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
    at REPLServer.Interface._ttyWrite (readline.js:830:14)
    at ReadStream.onkeypress (readline.js:109:10)
> originalStorageKeyHex = '0x0c'
'0x0c'
> ethUtil.pad(ethUtil.stripHexPrefix(originalStorageKeyHex), 32)
<Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 30 63>
> ethUtil.stripHexPrefix(originalStorageKeyHex)
'0c'
> ethUtil.pad(originalStorageKeyHex, 32)
<Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0c>
> 
```

**Comment by kumavis** [comment]
input interpretted as a string not a hexString, b/c stripHexPrefix returns a string not a buffer
